tasks:
  - name: Pull Docker Images
    before: |
      docker pull jenkins/jenkins
      docker pull maven:3.9.9-eclipse-temurin-17
      docker pull grafana/k6
      
  - name: Install k6
    before: |
      sudo gpg -k
      sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
      echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
      sudo apt-get update
      sudo apt-get install k6
      k6 --version

  - name: Run CI Infrastructure
    before: |
      sudo chmod 666 /var/run/docker.sock
      cd ci
      docker compose -f compose.yaml -f jenkins/compose.yaml build
      docker compose -f compose.yaml -f jenkins/compose.yaml up -d
      gp ports await 8080
      echo "Setting up CI infrastructure"
      sleep 60
      docker ps
      echo "CI infrastructure Ready"
