pipeline {
    agent any
    
    options {
    timeout(time: 5, unit: 'MINUTES')
  }
    stages {
        stage("Build Docker Image") {
            steps {
                sh '''
                docker image build -f app/Dockerfile -t swagger-petstore app
                '''
            }
        }
    }
}